### PR TITLE
DK Spells and Bar

### PR DESCRIPTION
**Pull request by Korbl**
Adding DK spells to CachedSpellData and buttons to ABCatagoryData

### CODE REVIEW

**Comment by Korbl** [comment]
Hurm. The PR also pulled in the updates to the Elixirs, Explosives, Flasks, Food, Gear, and Misc. I was hoping to make that a separate PR.

**Comment by MuffinManKen** [comment]
Can you change the DK Antimagic Shell/Zone so the right-click alternates rather than repeating?  This gives a lot more flexibility for the player.
"DEATHKNIGHT", ABGCode.GetSpellNameByName("Anti-Magic Shell"), ABGCode.GetSpellNameByName("Anti-Magic Zone"),
"DEATHKNIGHT", ABGCode.GetSpellNameByName("Anti-Magic Zone"), ABGCode.GetSpellNameByName("Anti-Magic Shell"),

**Comment by Korbl** [comment]
updated.

**Comment by MuffinManKen** [comment]
Great, thanks!

**Pull request merged**
